### ISSUE TITLE
When `onAdd` is called, state is not updated yet

### ISSUE THREAD

**Issue by Mykybo** [colyseus/colyseus#245]
When `onAdd` fires on an array, the state instance in room does not yet hold this new value.

This is not documented anywhere and is really unintuitive.

**Comment by endel** [comment]
I think we can consider this to be a bug. I've experienced the same thing recently on a game I'm working on, and it doesn't feel intuitive indeed. 

As the callbacks are triggered in order of decoding, the previously decoded fields should be available during `onAdd` inside arrays and maps. Apparently, they're currently not.

**Comment by endel** [comment]
I've released `@colyseus/schema@0.5.8` today making sure the encoding order follows the order of the fields are described in the schema: https://github.com/colyseus/schema/compare/73a0a88f6f76b0e8eba5d255ab325d00b8fcdd9b...fba507d4d1c1326f89783b4de0db9f1c7d7cfc30

**Comment by v0gler** [comment]
Hi @endel , the problem still exists in the current version and can be reproduced with your state room example. 
When another player joins the room the player map only contains the first user when the onAdd callback fires. 

![image](https://user-images.githubusercontent.com/25635896/82094096-b1f88280-96fc-11ea-84fa-90b21f0eedc1.png)

**Comment by endel** [comment]
@v0gler the schema callbacks are triggered during decoding time, so this is working as expected. You can see the new (arriving) `sessionId=wk2wS-QHC`, and only the previous ones (already decoded) are already available in the state.

**Comment by v0gler** [comment]
Hi @endel thanks for your fast reply :)
Is there an easy way to access the state after decoding? I need to access the playermap with all players after a new player joined.
