### ISSUE TITLE
[Bug]: Type errors in ArraySchema.d.ts

### ISSUE THREAD

**Issue by francislavoie** [colyseus/colyseus#648]
### Context

I'm playing around with a new fresh project using Colyseus, I was using the TOSIOS-hathora demo as a basis to get started.

### Bug description

When trying to run the server, I'm getting type errors from the schema package:

```
$ tsc
../../node_modules/@colyseus/schema/lib/types/ArraySchema.d.ts:35:5 - error TS2416: Property 'concat' in type 'ArraySchema<V>' is not assignable to the same property in base type 'V[]'.
  Type '(...items: (V | ConcatArray<V>)[]) => ArraySchema<V>' is not assignable to type '{ (...items: ConcatArray<V>[]): V[]; (...items: (V | ConcatArray<V>)[]): V[]; }'.
    Type 'ArraySchema<V>' is missing the following properties from type 'V[]': toReversed, toSorted, toSpliced, with

35     concat(...items: (V | ConcatArray<V>)[]): ArraySchema<V>;
       ~~~~~~

../../node_modules/@colyseus/schema/lib/types/ArraySchema.d.ts:44:5 - error TS2416: Property 'reverse' in type 'ArraySchema<V>' is not assignable to the same property in base type 'V[]'.
  Type '() => ArraySchema<V>' is not assignable to type '() => V[]'.
    Type 'ArraySchema<V>' is not assignable to type 'V[]'.

44     reverse(): ArraySchema<V>;
       ~~~~~~~
```

### Reproduction

[repro-colyseus.zip](https://github.com/colyseus/colyseus/files/13212506/repro-colyseus.zip)

### Steps to reproduce

1. `yarn`
2. `cd packages/server && npx tsc --noEmit`
3. See the errors :thinking: 

### Environment & Versions

Colyseus version: v0.15.9
NodeJS version: v18.18.2
TypeScript version: v5.2.2

**Comment by francislavoie** [comment]
Sorry, this probably belongs on https://github.com/colyseus/schema, I made the assumption this is a monorepo and didn't realize that repo existed. Feel free to move it.

**Comment by endel** [comment]
Hi @francislavoie, thank you for reporting and the reproduction project.

Here is a workaround while we don't have a proper fix for this - add `skipLibCheck` to `tsconfig.json` file:

```json
{
  "compilerOptions": {
    // ...
    "skipLibCheck": true,
    // ...
  }
}
```

**Comment by endel** [comment]
Should be fixed in `@colyseus/schema` version `2.0.21` https://github.com/colyseus/schema/commit/bea23c03537d5f7018e5277788d19bd27c02bb11 🙏

**Comment by francislavoie** [comment]
Thanks!

**Comment by sandrooco** [comment]
Hi @endel, I still face this issue with 2.0.34. Any ideas how to fix it?
